spring:
  application:
    name: identity-service
  datasource:
    url: ${IDENTITY_DB_URL:jdbc:postgresql://postgres:5432/identity_db}
    username: ${IDENTITY_DB_USER:identity_db}
    password: ${IDENTITY_DB_PASSWORD:identity_db}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

flyway:
  enabled: true
  baseline-on-migrate: true

server:
  port: 8082
