spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://postgres:5432/order_db}
    username: ${ORDER_DB_USER:order_db}
    password: ${ORDER_DB_PASSWORD:order_db}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8083

external:
  product-service:
    base-url: ${PRODUCT_SERVICE_URL:http://product-service:8082}
  promotion-service:
    base-url: ${PROMOTION_SERVICE_URL:http://promotion-service:8084}
  openrouteservice:
    base-url: ${OPENROUTESERVICE_BASE_URL:https://api.openrouteservice.org}
    api-key: ${OPENROUTESERVICE_API_KEY:}
