spring:
  application:
    name: report-service
  datasource:
    url: ${REPORT_DB_URL:jdbc:postgresql://postgres:5432/report_db}
    username: ${REPORT_DB_USER:report_db}
    password: ${REPORT_DB_PASSWORD:report_db}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8085
